#!/usr/bin/env bash
# nlir showcase · msm3 · COMPOSITION — concept→list→exact-reduce ("useful work")
#
# HONEST FRAMING (2026-07-09, from Harry's "give nlir richer moves that COMPOSE"):
# the third leg of the fusion story. move-msm1-mathy.sh is the exact SUBSTRATE;
# move-msm1-fusion.sh is the broad FUSION taste; move-msm3-self-verify.sh is the TRUST
# story. This one is COMPOSITION: concept-level semantic ops that emit a LIST, split by
# `//`, then fed to the EXACT reducers ($map/$fold/$len/$filter). Describe a set by
# meaning → turn it into structure → compute over it exactly. numpy has no notion of
# meaning; a raw prompt has no reliable exactness or composition. nlir does both halves.
#
# LIVE — needs a model (llm mode). Outputs are model-dependent; the reliability caveats
# are inline so it teaches the discipline, not just the trick. NEVER CI-assert these.
#
# THE COMPOSITIONAL GLUE is the existing `//` split (string→list) — no new engine
# primitive was needed (the semantic ops emit comma-sep strings, `//` lists them, the
# exact reducers compose). The concept→list surface is `=>'…'//', '` TODAY; a terser
# dedicated op (`$syn` etc., aur-1's lane) is optional future ergonomics — the
# composition STORY is unchanged.
set -euo pipefail
cd "$(dirname "$0")/.."
NLIR="${NLIR:-./target/release/nlir}"
[ -x "$NLIR" ] || { echo "build first: cargo build --release (or set NLIR=...)"; exit 1; }
CFG="${NLIR_CONFIG:-config.example.yaml}"

say() { printf '\n\033[1m%s\033[0m\n' "$1"; }
why() { printf '   \033[2m(%s)\033[0m\n' "$1"; }
# run EXPR — evaluate a LIVE (llm-mode) expression; output is model-dependent.
# _sep=', ' renders list results comma-joined on one line.
run() { printf '  => '; "$NLIR" --config "$CFG" --mode llm --quiet -e "_sep=', ';$1" 2>&1 | paste -sd' ' -; }

say "COMPOSITION — meaning turned into structure, computed exactly (LIVE; needs a model)"
why "concept-level semantic ops emit a LIST; // splits it; the exact reducers compose over it. The 'useful work' Harry pushed for — neither a spreadsheet (no meaning) nor a chatbot (no reliable exactness/composition) does both halves."

say "1. ANTONYM OVER A LIST — a semantic op mapped across items (pure composition)"
why "\$map applies ! (opposite) to each item. ! is three-transport-locked (bd-fddeae) — it now returns a distinct ANTONYM (cold, not 'not hot'), stable even for the weak words that used to fall back to negation. Exact structure (\$map), semantic leaf (!)."
run "\$map%({!\$0},['hot','fast','up'])"

say "2. CONCEPT → LIST → EXACT COUNT — the fusion beat"
why "generate a list by meaning, split with //, count with the exact \$len. RELIABILITY: the count is exact ONLY because we PIN 'exactly three' — list LENGTH is model-supplied, so pin it or live-gate; NEVER CI-assert an unpinned semantic count (bd-429d87)."
run "\$len%(=>'list exactly three synonyms for happy, comma-separated'//', ')"

say "3. GENERATE → SPLIT → FILTER — two semantic acts bracketing exact structure"
why "\$filter keeps only the items that ~> 'a fruit', over a list GENERATED by meaning. Generate-by-meaning + judge-by-meaning wrap an exact filter/split: numpy can neither generate nor judge; a prompt can't do the exact filter-structure reliably."
run "\$filter%({\$0~>'a fruit'},=>'list six kitchen items mixing fruits and non-fruits, comma-separated'//', ')"

say "4. CONCEPT → LIST → SEMANTIC FOLD — reduce a generated list back to one text"
why "\$fold joins the generated synonyms with & (a semantic 'and'). concept→list→fold: the list-structure is exact, the leaves and the join are semantic. Compose the exact scaffolding with semantic reducers, not just numeric ones."
run "\$fold%({\$0&\$1},=>'list three synonyms for happy, comma-separated'//', ')"

say "THE DISCIPLINE — which half is exact, which is judged"
why "EXACT (reproducible): the // split, and the \$map/\$fold/\$len/\$filter structure — same every run. JUDGED (model-dependent): the generation, each per-item ~>, the antonym. Report the exact result; LIVE-CAPTION the judged parts; anchor any self-check on a CONTENT property, never style (bd-3a589a). Verified on ms-mac (the divergent transport); the ! op holds three-transport (bd-fddeae)."
why "the pattern: describe a set in meaning → // it into structure → compute exactly → live-caption the fuzzy leaves. That is composition you can trust — the richer semantic vocabulary Harry asked for, snapping cleanly onto the exact machinery."
